- README.md
Formbricks is an open-source privacy-first Experience Management suite based in Germany.
> Add Formbricks to productivity tools

- README.md
From what I know, Axelera is the EU’s only AI hardware manufacturer.
> Update README.md with Axelera AI

- README.md
- added new sections and projects suggested by community
- removed chart for the moment
> feat : some features

- README.md
I've added the company where I work, who offer hardware + AI powered tools to chart and reduce food waste in professional kitchens.
> Add orbisk.com

- README.md
* added missing "Music and Travel" category to Index
* moved "Music and Travel" category to adhere to alphabetical ordering
* added "Network Tools and Apps" category
* added IPXO to "Network Tools and Apps" category
> Minor reorganization and new "Network Tools and Apps" category

- README.md
Adds Penpot, see:
- https://penpot.app/
- https://github.com/penpot/penpot
> Adds Penpot

- README.md
Fixing the URLs for Counter and Tinylytics
> Fixing a couple of URLs

- README.md
Adds crowdfunding section, with most of the features platforms in this [article](https://whydonate.com/en/blog/top10-crowdfunding-platforms-europe).
Closes https://github.com/uscneps/Awesome-European-Tech/issues/35
> Add crowdfunding platforms section

- README.md
Added:
- Deezer
- Qobuz
- AnyType
- Mailo
> Added 4 new services

- README.md
I believe this might be the current site of this project as the previous one is not working.
> Update website for Wide Angle Analytics

- README.md
- bunq - popular alternative to Revolut and Monzo, currently available in 6 countries
- Infomaniak - already on the list, but not in VPS section
- PrivateVPN, ProtonVPN - adding more providers
I also fixed the alphabetical order in VPN section by moving GooseVPN higher up
> Add more services

- README.md
> Add a gaming projects section

- README.md
SKRED app was pointed to a false URL and false flag
> Update SKRED app

- README.md
I'd like to propose adding ZenML (https://github.com/zenml-io/zenml) (https://zenml.io) to this list. ZenML offers production-grade MLOps systems, handling evaluation, monitoring, and deployment at scale. I don't work with ZenML but am rather a customer and contributor, as we've been using it for more than a year now. ZenML has a managed solution in the cloud but also an open source offering that can be self hosted.
I think it meets the criteria -
* Compliance: see item 10 at https://www.zenml.io/privacy-policy
* EU HQ: it is based in Munich, Germany.
* Technology focus:  most definitely.
> Add ZenML to list

- README.md
Added: Ubisoft store to gaming section
> add Ubisoft store

- README.md
Add services: ALTCHA, GetResponse, RenderForm, SimpleLocalize, Krystal, Plausible
> Add services

- README.md
ESET is an Antivirus and Cybersecurity company founded in Slovakia.
> Add ESET to the list

- README.md
Scalable Capital is a European fintech company based in Munich, Germany.
> Add Scalable Capital to the list

- README.md
Olimex is a Bulgarian company developing and selling all sorts of embedded development boards.
> Add Olimex to the list

- README.md
> Organic Maps is Estonian

- README.md
> Change Cylib url

- README.md
Based in Liechtenstein, strong focus on privacy. 
https://paretosecurity.com/
I also added some missing capitalization, let me know if I should remove it.
> Add Pareto Security to Cybersecurity

- README.md
This library is used by over 20 million projects:
https://flowbite.com/
And it's made in the EU!
> add(flowbite): open-source UI library for designers and developers

- .github/CONTRIBUTING.md
> Fix a typo in CONTRIBUTING

- README.md
Found a misspellings.
Please consider using https://github.com/crate-ci/typos
> Fix typo in CALMS description

- .github/FUNDING.yml
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
> Displaying a sponsor button

- README.md
This PR adds three awesome European tech companies:
[Ibexa](https://ibexa.co) - a DXP vendor,
[Raptor](https://www.raptorservices.com/customer-data-platform/) - a CDP vendor,
[Quable](https://www.quable.com/en) - a PIM vendor
> Added Ibexa, Raptor and Quable

- README.md
Hello !
I wanted to add Brevo to Marketing tools section.
Thanks in advance.
> README: Add Brevo to Marketing Tools

- README.md
Hello,
Sorry there was a typo that I've seen only after merging...
Thanks in advance !
> README: update typo Brevo link

- README.md
I find it interesting to expand your repository instead of creating a new one. 
Good job! Greetings from Spain!
> Added mrdomain/dondominio to README.md

- README.md
- Move Brevo to CRM
- Rename "Customer Data Platforms" to "Customer Relationship Management"
- Add Atomic CRM (https://marmelab.com/atomic-crm/), open-source CRM created and maintained by a Fench company (Marmelab).
> Add CRM section

- README.md
Added in alphabetical order. 
1) European supplier, company on European territory
2) Own network 
Greetings!
> Added some vps providers to README.md

- README.md
Add new VPS providers from my private list to readme.md
Will propose format improvements in an issue when I have free time
Greetings!
> New VPS providers to README.md

- README.md
Docs is the result of a joint effort lead by the French 🇫🇷🥖(DINUM) and German 🇩🇪🥨 governments (ZenDiS). Source: https://docs.numerique.gouv.fr/login/
> Add "Docs" productivity tool

- README.md
- Added OVHcloud as part of the VPS providers list (with vps url)
Cheers!
> Added OVHcloud in vps section in README.md

- README.md
I added a new category, since we all know uptime monitors, it is good to know about some less known and especially European.
Greetings!
> New category uptime monitoring services added

- README.md
New category about Identity related solutions (IAM) with some European solutions.
Related to #3
> Create IAM section

- README.md
Please accept the addition of OpenCloud, our new open source file sync and share solution.
> Add OpenCloud entry

- README.md
> Surfshark listed as VPS instead of as a VPN

- README.md
Added the Belgium based employee advocacy company Ambassify
> Add Ambassify

- .github/workflows/check-links.yml
- README.md
First of all, thank you so much for this repo. It gives a little hope for those who feel stuck in US services in these grim times.
There's a bunch of broken links in the README, this automated check will help to keep the README quality high and remove broken links.
The check will be executed on pull requests, on merge to main branch and on every day basis. This is subject to change if you prefer something else @uscneps 
Under the hood, [lychee](https://lychee.cli.rs/) is used and it's GitHub Action integration: https://github.com/lycheeverse/lychee-action
Here's how it looks: https://github.com/limonte/Awesome-European-Tech/actions/runs/14547155315
> feat: automated check for broken links

- .github/workflows/check-links.yml
follow-up for my previous PR #122 
it should help with flaky failures: https://github.com/uscneps/Awesome-European-Tech/actions/runs/14548341741/job/40816574937
> fix: increase the timeout to decrease flaky failures

- README.md
Prosopo Procaptcha is a UK based, privacy focussed, GDPR compliant CAPTCHA solution for protecting against bots and automated attacks.
Conditions:
> Add Prosopo Procaptcha

- README.md
Added a new section "Scientific software" including some first entries as discussed in https://github.com/uscneps/Awesome-European-Tech/issues/127
> Added "Scientific software" section

- README.md
Pr proposes to add Cubbit solution. 
Cubbit provides software to build a private and geo-distributed object storage where resiliency, control, sovereignty, and lower costs are the core fundamentals.
We're a very deep tech italian company and I believe a good fit for the cloud section of the list.
Feel free to reach out!
More on [Cubbit](https://www.cubbit.io/)
> Add Cubbit to Cloud list

- README.md
Haven't used them personally, but they are from the EU and I have friends that use them.
> adding GleSYS

- README.md
add Thalassa Cloud to Cloud category
> add Thalassa Cloud to Cloud category

- README.md
DNS4EU as a secure-infrastructure project provides a protective, privacy-compliant, and resilient DNS service to strengthen digital sovereignty and security for EU citizens, governments, and critical infrastructure. Supported by the European Commission.
> Add DNS4EU

- README.md
Tebi.io is a Cyprus based object storage provider.
> Added Tebi.io to cloud section

- README.md
Adding Proton's new Authenticator to the Authenticators list, and Raisin to the FInTech list. Cheers!
> Add Proton Authenticator and Raisin

- README.md
- Added Passwork.pro, a corporate password manager from Spain
- Passwork.pro provides secure password management solutions for businesses
- Enhances the cybersecurity tools section in our European products catalog
- Link: https://passwork.pro
> feat: add Passwork.pro corporate password manager from Spain

- README.md
Adds new section for Photography in toc and as a headline, since Pixii won't fit any other section.
> Adds Photography section with Pixii
